services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./backend/assets:/app/assets

  frontend:
    build:
      context: ./frontend
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always   
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/db.sql:/docker-entrypoint-initdb.d/01_schema.sql

volumes:
  pgdata: