services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
      JWT_SECRET: AMINOTSECRETENOUGHFORYOU???YOUCANTCRACKTHIS!!!IAMTOOSTRONGFORYOUTOCRACK!!!ff23083

      #Please configure with your own google client id here...
      VITE_GOOGLE_CLIENT_ID: 1004129401046-42tsa627e6q856qqrbghtiue4kouvfgv.apps.googleusercontent.com
    volumes:
      - ./uploads:/app/uploads
      - ./backend/src/assets/temp:/app/src/assets/temp

  frontend:
    build:
      context: ./frontend
      args:
        VITE_GOOGLE_CLIENT_ID: 1004129401046-42tsa627e6q856qqrbghtiue4kouvfgv.apps.googleusercontent.com
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/db.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/dummyData.sql:/docker-entrypoint-initdb.d/02_data.sql
volumes:
  pgdata:
